title: DKorablin repositories
description: The list of releases from some of private repositories

defaults:
  -
    scope:
      path: ""   # applies to all files
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed